Repository proyecto-arima/webapp, pull requests merged in 2024-10, with the labels that each got.

#72 71 fix contents
  src/pages/courses/CourseCreationPage.tsx
  src/pages/courses/EditCoursePage.tsx
  src/pages/courses/EditSectionPage.tsx
  src/pages/courses/SectionCreationPage.tsx
  src/pages/sections/EditContentPage.tsx
  src/pages/sections/SectionContentCreation.tsx
  src/pages/sections/SectionContentDashboardForm/SectionContentDashboardFormTeachers.tsx
  src/redux/slices/sections.ts
Labels: feature-proyecto

#83 #81 - Imagenes como archivos en cursos y secciones funcionando
  src/pages/courses/CourseCreationPage.tsx
  src/pages/courses/EditCoursePage.tsx
  src/pages/courses/EditSectionPage.tsx
  src/pages/courses/SectionCreationPage.tsx
Labels: feature-proyecto

#86 84 modificar rol de usuario
  src/pages/students/StudentDashboardPage.tsx
  src/pages/teachers/TeacherDashboardPage.tsx
Labels: feature-proyecto

#87 #85 - Matriculacion del estudiante funcionando
  src/components/Sidebar.tsx
  src/pages/courses/CourseCreationPage.tsx
  src/pages/courses/CourseSearchPage.tsx
  src/routes/CourseRouter.tsx
Labels: feature-proyecto

#89 88 fix secciones v2
  src/pages/courses/CourseDashboardPage.tsx
  src/pages/courses/CourseDetailPage.tsx
  src/pages/courses/EditCoursePage.tsx
  src/pages/courses/EditSectionPage.tsx
  src/pages/courses/SectionCreationPage.tsx
Labels: feature-proyecto

#99 Google integration
  package-lock.json
  package.json
  src/components/LoginForm.tsx
  src/components/RecoverPasswordForm.tsx
  src/models/.keep
  src/pages/auth/LoginPage.tsx
  src/pages/auth/RecoverPasswordPage.tsx
Labels: feature-proyecto

#93 92 fix cursos y secciones rol docente
  src/pages/courses/CourseCreationPage.tsx
  src/pages/courses/CourseDashboardPage.tsx
  src/pages/courses/EditCoursePage.tsx
  src/pages/courses/EditSectionPage.tsx
  src/pages/courses/StudentLinkingPage.tsx
Labels: bug

#96 #94 - Boton de ver mis cursos y nuevo span funcionando y mostrado
  src/components/Sidebar.tsx
Labels: feature-proyecto

#115 #107 - Added new files for massive users creation
  package-lock.json
  package.json
  src/components/Sidebar.tsx
  src/pages/Index.tsx
  src/pages/directors/UserCreationMassivePage.tsx
  src/pages/students/StudentDashboardPage.tsx
  src/pages/teachers/TeacherDashboardPage.tsx
Labels: feature-proyecto

#122 Fixs sprint 8
  src/pages/directors/StudentsSurveyDashboardPage.tsx
  src/pages/directors/TeachersSurveyDashboardPage.tsx
  src/pages/directors/UserCreationMassivePage.tsx
  src/pages/students/StudentDashboardPage.tsx
  src/pages/teachers/TeacherDashboardPage.tsx
  src/pages/teachers/TeacherStudentsSurveyDashboardPage.tsx
Labels: bug, mejoras-upgrades
